// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createOffer = `-- name: CreateOffer :exec
INSERT
OR IGNORE INTO offers (id, title, company, location, posted_at)
VALUES
    (?, ?, ?, ?, ?)
`

type CreateOfferParams struct {
	ID       string
	Title    string
	Company  string
	Location string
	PostedAt time.Time
}

func (q *Queries) CreateOffer(ctx context.Context, arg *CreateOfferParams) error {
	_, err := q.db.ExecContext(ctx, createOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.PostedAt,
	)
	return err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO
    queries (keywords, location)
VALUES
    (?, ?) RETURNING id, keywords, location, created_at, queried_at
`

type CreateQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) CreateQuery(ctx context.Context, arg *CreateQueryParams) (*Query, error) {
	row := q.db.QueryRowContext(ctx, createQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
	)
	return &i, err
}

const createQueryOfferAssoc = `-- name: CreateQueryOfferAssoc :exec
INSERT INTO
    query_offers (query_id, offer_id)
VALUES
    (?, ?)
`

type CreateQueryOfferAssocParams struct {
	QueryID int64
	OfferID string
}

func (q *Queries) CreateQueryOfferAssoc(ctx context.Context, arg *CreateQueryOfferAssocParams) error {
	_, err := q.db.ExecContext(ctx, createQueryOfferAssoc, arg.QueryID, arg.OfferID)
	return err
}

const getQuery = `-- name: GetQuery :one
SELECT
    id, keywords, location, created_at, queried_at
FROM
    queries
WHERE
    keywords = ?
    AND location = ?
`

type GetQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) GetQuery(ctx context.Context, arg *GetQueryParams) (*Query, error) {
	row := q.db.QueryRowContext(ctx, getQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
	)
	return &i, err
}

const listOffers = `-- name: ListOffers :many
SELECT
    o.id, o.title, o.company, o.location, o.posted_at, o.created_at
FROM
    queries q
    JOIN query_offers qo ON q.id = qo.query_id
    JOIN offers o ON qo.offer_id = o.id
WHERE
    q.id = ?
    -- AND DATE(o.posted_at) >= ?
ORDER BY
    o.posted_at DESC
`

func (q *Queries) ListOffers(ctx context.Context, id int64) ([]*Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueryTS = `-- name: UpdateQueryTS :exec
UPDATE queries
SET
    queried_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

func (q *Queries) UpdateQueryTS(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateQueryTS, id)
	return err
}
